### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by ghost** [HelingZhang/CoqGym#2]

**Comment by brando90** [comment]
Meeting
* P(Y=Tree | X=Thm)
    * TODO: read on the the lit for phylogenetic trees
    * e-mail so some professor related this about it
* HOList:
    * https://sites.google.com/view/holist/home
* Gabrielle: RL
    * https://arxiv.org/pdf/1904.03241.pdf
    * https://arxiv.org/abs/1905.10501
    * Read/familiarize with those techniques with the goal to implement a prototype for CoqGym RL
* Heling: Supervised
    * https://arxiv.org/abs/1905.10006
    * Read/familiarize with those techniques with the goal to implement a prototype for CoqGym SL
    * future: how to do tree search with CoqHammer and our ML prover
* Brando:
    * read on the the lit for phylogenetic trees
* TODO:
    * differentiation Hammers
        * formulating a problem makes sense
        * having embeding formulas be input
    * Sketching
        * reading phylogenetic trees

**Comment by brando90** [comment]
Bruijn nameless representations

http://fsl.cs.illinois.edu/index.php/CS522_-_Programming_Language_Semantics_(Fall_2018)
